definitions:
  dto.TaskDTO:
    properties:
      created_at:
        type: string
      finished_at:
        type: string
      id:
        type: string
      playbook:
        description: 例如 "deploy.yml"
        type: string
      started_at:
        description: 使用指標(pointer)來允許 null
        type: string
      status:
        type: string
    type: object
info:
  contact: {}
paths:
  /tasks:
    post:
      consumes:
      - application/json
      description: 接收 JSON body 來建立一個新的待處理任務
      parameters:
      - description: 要建立的任務資訊 (目前僅為範例，未來會簡化)
        in: body
        name: task
        required: true
        schema:
          $ref: '#/definitions/dto.TaskDTO'
      produces:
      - application/json
      responses:
        "201":
          description: 成功建立的任務
          schema:
            $ref: '#/definitions/dto.TaskDTO'
        "400":
          description: 無效的請求
          schema:
            type: string
      summary: 建立一個新任務
      tags:
      - Tasks
  /tasks/{task_id}:
    get:
      description: 根據 task_id 取得單一任務的詳細資訊
      parameters:
      - description: 任務 ID
        in: path
        name: task_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 成功取得的任務
          schema:
            $ref: '#/definitions/dto.TaskDTO'
        "400":
          description: 無效的 ID
          schema:
            type: string
        "404":
          description: 找不到任務
          schema:
            type: string
      summary: 取得一個特定任務
      tags:
      - Tasks
swagger: "2.0"
